# Generated by Django 4.0.2 on 2022-04-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwmodel',
            old_name='ean',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='inwmodel',
            old_name='quantity',
            new_name='Ilosc',
        ),
        migrations.RenameField(
            model_name='inwmodel',
            old_name='akc_name',
            new_name='Nazwa',
        ),
    ]
