# Generated by Django 4.0.2 on 2022-04-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0003_alter_inwmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inwmodel',
            unique_together=set(),
        ),
    ]
