# Generated by Django 4.0 on 2022-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0004_alter_inwmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwmodel',
            name='EAN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inwmodel',
            name='Nazwa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
