# Generated by Django 4.0 on 2022-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0005_alter_inwmodel_ean_alter_inwmodel_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwmodel',
            name='Nazwa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
