# Generated by Django 4.0.2 on 2022-05-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0006_alter_inwmodel_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='inwmodel',
            old_name='Nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inwmodel',
            old_name='Ilosc',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='inwmodel',
            name='upload',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='inw.uploadmodel'),
            preserve_default=False,
        ),
    ]
