# Generated by Django 4.0.2 on 2022-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0007_uploadmodel_rename_nazwa_inwmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(max_length=200, null=0, unique=True),
        ),
    ]
