# Generated by Django 4.0.2 on 2022-05-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0009_alter_inwmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='quantity',
        ),
    ]
