# Generated by Django 4.0.2 on 2022-05-15 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inw', '0010_remove_uploadmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
