# Generated by Django 4.0.2 on 2022-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0012_alter_uploadmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
