# Generated by Django 4.0.2 on 2022-05-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0013_alter_uploadmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwmodel',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to='inw.uploadmodel'),
        ),
    ]
