# Generated by Django 4.0.2 on 2022-05-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0014_alter_inwmodel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
