# Generated by Django 4.0.2 on 2022-05-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inw', '0015_alter_uploadmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
